### PR TITLE
Project setup

### LINKED ISSUE #2: Window renders at wrong resolution until it is resized
## Expected Behavior

When the program starts up, the game viewport takes up the whole screen. The player can move anywhere in the screen.

## Current Behavior

The game viewport takes up about a quarter of the screen, the player does not render correctly and cannot move to all parts of the screen.

### PR DESCRIPTION
**Pull request by dislocated-su**
Implementing most important things like movement, collisions, rendering, etc.

Please look at this code as it is important.

### CODE REVIEW

**Comment by dislocated-su** [comment]
This now fixes #2.

**Comment by roh518** [comment]
Movement is good, jittering and and slight backwards movements all removed, with the screen panning a bit longer than movement creating a nice look. Should we merge into main soon and branch off individually?

**Comment by dislocated-su** [comment]
Yeah, sounds good. Need a full review from anyone then we can merge. I have no idea what causes the jitter, I tried to link velocity to deltatime which seemed to fix it on my end. I have looked at previous versions and the jitter persists.

**Review by roh518 — DISMISSED** [review]

**Review by roh518 — APPROVED** [review]
all good

**Pull request merged**
